name: GitHub Script
author: GitHub
description: Run simple scripts using the GitHub client
branding:
  color: blue
  icon: code
inputs:
  script:
    description: The script to run
    required: false
    default: "const fs = require('fs');
      const axios = require('${process.env.GITHUB_WORKSPACE}/node_modules/axios');
      const planOutput = '${{ steps.plan.outputs.stdout }}';
      const urlRegex = app.terraform.io/app/shoprunner/[A-Za-z0-9-]*/runs/run-[A-Za-z0-9]*;
      const match = planOutput.match(urlRegex);
      const urlSplit = match[0].split('/');
      const planApiUrl = 'https://app.terraform.io/api/v2/runs/${urlSplit[urlSplit.length - 1]}/plan'
      const planResult = await axios.request(planApiUrl, {
      headers: {
      accept: 'application/json',
      authorization: 'Bearer ${{ secrets.TF_API_TOKEN }}'
      }
      });
      const apiUrl = 'https://app.terraform.io${planResult.data.data.links['json-output']}';
      const result = await axios.request(apiUrl, {
      headers: {
      accept: 'application/json',
      authorization: 'Bearer ${{ secrets.TF_API_TOKEN }}'
      }
      });

      const tfplan = result.data;
      const tfplanOutput = JSON.stringify(tfplan);

      fs.writeFileSync('tfplan.json', tfplanOutput);
      return tfplanOutput;"
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  debug:
    description: Whether to tell the GitHub client to log details of its requests
    required: false
    default: "false"
  user-agent:
    description: An optional user-agent string
    required: false
    default: actions/github-script
  previews:
    description: A comma-separated list of API previews to accept
    required: false
  result-encoding:
    description: Either "string" or "json" (default "json")—how the result will be encoded
    required: false
    default: json
outputs:
  result:
    description: The return value of the script, stringified with 'JSON.stringify'
runs:
  using: node12
  main: dist/index.js
