name: 'action-terraform-cloud'
description: 'Github Action running terraform core bits'
author: 'ShopRunner'
inputs:
  command:
    required: false
    description: 'TBD'
    default: 'plan'
  tf_plan_output:
    required: false
    description: 'The stdout terraform plan'
  tf_api_token:
    required: true
    description: 'The API token used to access Terraform Cloud'
  tf_organization:
    required: true
    description: 'The Terraform organization account you are accessing.'
    default: 'shoprunner'
runs:
  using: 'node12'
  main: 'dist/index.js'
